### ISSUE TITLE
hugo serve: Error executing zigdoctest for [assets/.../1-simple-executable/build.zig]: AccessDenied

### ISSUE THREAD

**Issue by Des-Nerger** [ziglang/www.ziglang.org#358]
Tried to run `www.ziglang.org` locally, but `zig-doctest` failed somehow. Its version was [the most recent one cloned from GitHub](https://github.com/kristoff-it/zig-doctest/tree/fa943932a9941c6cb6af37a0f43aafed4907d24c). Tried to built `zig-doctest` with both the `0.13.0-dev.73+db890dbae` and `0.13.0-dev.75+5c9eb4081` versions of Zig, but the result was the same.

```
$ ~/.go/bin/hugo serve
[Zig Doctest] TESTING <assets/zig-code/build-system/1-simple-executable/build.zig>...
[Zig Doctest] TESTING <assets/zig-code/build-system/1-simple-executable/hello.zig>...
[Zig Doctest] TESTING <assets/zig-code/build-system/10-release/hello.zig>...
[Zig Doctest] TESTING <assets/zig-code/build-system/10-release/build.zig>...
Start building sites … 
panic: Error executing zigdoctest for [assets/zig-code/build-system/1-simple-executable/build.zig]: error: AccessDenied

Build failed unexpectedly
zig build --color on --cache-dir ../../../../../../../../../media/c/Documnts/src/zig/www.ziglang.org/doctest-68a61b5b/zig-cache --prefix ../../../../../../../../../media/c/Documnts/src/zig/www.ziglang.org/doctest-68a61b5b/zig-out --summary all 
error: BuildFailed
/media/c/Documnts/src/zig/kristoff-it/zig-doctest/src/doctest/BuildSystemCommand.zig:87:25: 0x10b0c2a in run__anon_6208 (doctest)
                        return error.BuildFailed;
                        ^
/media/c/Documnts/src/zig/kristoff-it/zig-doctest/src/main.zig:376:5: 0x10b1df7 in do_build_system__anon_6191 (doctest)
    try @import("doctest/BuildSystemCommand.zig").run(
    ^
/media/c/Documnts/src/zig/kristoff-it/zig-doctest/src/main.zig:100:21: 0x10bc254 in main (doctest)
                    try do_build_system(allocator, &iterator, in_file, buffered_out_stream.writer());
                    ^
: exit status 1

goroutine 8 [running]:
github.com/gohugoio/hugo/tpl/zig.(*Namespace).Warmup.func1(0xc000474000, 0xc0005c18e0)
	/home/username/.go/src/github.com/kristoff-it/hugo/tpl/zig/doctest.go:107 +0xba
created by github.com/gohugoio/hugo/tpl/zig.(*Namespace).Warmup
	/home/username/.go/src/github.com/kristoff-it/hugo/tpl/zig/doctest.go:99 +0x74
```

**Comment by kristoff-it** [comment]
We're switching to https://zine-ssg.io, once the transition is done we expect the tooling to break less often.
